version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: financial_portfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Usando o volume nomeado 'mysql_data' aqui
      - mysql_data:/var/lib/mysql
      # Mapeamento para scripts SQL de inicialização
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: financial_portfolio_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      ["8080:80"]
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  # Definindo o volume nomeado para persistência
  mysql_data:
    driver: local